### ISSUE TITLE
cannot open shared obj. file: {libc.musl-x86_64.so.1, libstdc++.so.6}

### ISSUE THREAD

**Issue by MarianSielenkaemper** [PyPlanet/maniaplanet-docker#5]
When building, these errors occur: 
`./ManiaPlanetServer: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory` ,
`./ManiaPlanetServer: error while loading shared libraries: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory` .
I don't know if these libraries should be in place from https://github.com/sgerrand/alpine-pkg-glibc or are just missing accidentily. However, when using
`RUN apk-add libstdc++ musl`
and adding them to the library path:
`ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib/:/lib/"`, the docker seems to work again.
I am not a docker expert, so this is most certainly not the most elegant solution, but at least the docker runs the server now.

**Comment by tomvlk** [comment]
@MarianSielenkaemper I applied a similar 'hack' to the actual image itself as you can see in the dockerfile.
Did you got it working with the method above? I will try this on my own setup in the upcoming days and with the new dedicated of MP 4.1 (or did you try it with 4.1?)

**Comment by MarianSielenkaemper** [comment]
@tomvlk Yes, this fixes the issue. I also bumped the version to MP4.1, which needs libuuid. Thank you very much for this docker!
